CREATE TABLE SEQUENCE (
    SEQ_NAME varchar(50) NOT NULL,
    SEQ_COUNT decimal(15,0) NOT NULL
);

CREATE TABLE ALUMNO (
    ALUMNO_ID int NOT NULL,
    NOMBRE varchar(255),
    PRIMER_APELLIDO varchar(255),
    SEGUNDO_APELLIDO varchar(255),
    EMAIL varchar(255),
    PRIMARY KEY (ALUMNO_ID)
);

CREATE TABLE USUARIO_ROLE (
    ROLE_ID int NOT NULL,
    ROLE_NAME varchar(10) NOT NULL,
    PRIMARY KEY (ROLE_ID)
   
);

CREATE TABLE ES_PROV (
    ES_PROV_ID int NOT NULL,
    ES_PROV_CD varchar(2) NOT NULL,
    ES_PROV_NM varchar(30) NOT NULL,
    PRIMARY KEY (ES_PROV_ID)
);

CREATE TABLE DIRECCION_TYPE (
    DIRECCION_TYPE_ID int NOT NULL,
    DIRECCION_TYPE_CODE varchar(1) NOT NULL,
    DIRECCION_TYPE_TEXT varchar(20) NOT NULL,
    PRIMARY KEY (DIRECCION_TYPE_ID)
);

CREATE TABLE DIRECCION (
    DIRECCION_ID int NOT NULL,
    DIRECCION_TYPE_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    PRIMARY KEY (DIRECCION_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID),
FOREIGN KEY (DIRECCION_TYPE_ID) REFERENCES DIRECCION_TYPE(DIRECCION_TYPE_ID)
);

CREATE TABLE ES_CIUDAD (
    ES_CIUDAD_ID int NOT NULL,
    ES_CIUDAD_NM varchar(30) NOT NULL,
    CP varchar(5) NOT NULL,
    ES_PROV_ID int NOT NULL,
    PRIMARY KEY (ES_CIUDAD_ID),
    FOREIGN KEY (ES_PROV_ID) REFERENCES ES_PROV(ES_PROV_ID)
);

CREATE TABLE TELEFONO_TYPE (
    TELEFONO_TYPE_ID int NOT NULL,
    TELEFONO_TYPE_CD varchar(1) NOT NULL,
    TELEFONO_TYPE_TEXT varchar(20) NOT NULL,
    PRIMARY KEY (TELEFONO_TYPE_ID)
);

CREATE TABLE TELEFONO (
    TELEFONO_ID int NOT NULL,
    TELEFONO_TYPE_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    PRIMARY KEY (TELEFONO_ID),
    FOREIGN KEY (TELEFONO_TYPE_ID) REFERENCES TELEFONO_TYPE(TELEFONO_TYPE_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID)
);

CREATE TABLE APP_USUARIO (
    APP_USUARIO_ID int NOT NULL,
    USUARIO_NAME varchar(15),
    PASSWORD varchar(15),
    PRIMARY KEY (APP_USUARIO_ID)
);

CREATE TABLE ITEM (
    ITEM_ID int NOT NULL,
    ITEM_NUMERO varchar(10) NOT NULL,
    ITEM_SHORT_DESC varchar(100) NOT NULL,
    ITEM_LONG_DESC varchar(100) NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE ALUMNO_ORDER (
    ALUMNO_ORDER_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    ORDER_NUMERO varchar(255),
    ORDER_DESCRIPTION varchar(255),
    PRIMARY KEY (ALUMNO_ORDER_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID)
);

CREATE TABLE ORDER_ITEM (
    ALUMNO_ORDER_ID int NOT NULL,
    ALUMNO_ORDER int NOT NULL,
    ITEM_ID int NOT NULL,
    PRIMARY KEY (ALUMNO_ORDER),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (ALUMNO_ORDER_ID) REFERENCES ALUMNO_ORDER(ALUMNO_ORDER_ID)
);

CREATE TABLE APP_USUARIO_ROLE (
    APP_USUARIO_ID int NOT NULL,
    ROLE_ID int NOT NULL,
    PRIMARY KEY (APP_USUARIO_ID, ROLE_ID),
    FOREIGN KEY (APP_USUARIO_ID) REFERENCES APP_USUARIO(APP_USUARIO_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES USUARIO_ROLE(ROLE_ID)
);
