/*
CREATE TABLE `SEQUENCE` (`SEQ_NAME` varchar(50) NOT NULL, `SEQ_COUNT` decimal(15,0) NOT NULL
)


CREATE TABLE `ALUMNO` (`ALUMNO_ID` int NOT NULL, `NOMBRE` varchar(20) NOT NULL, `PRIMER_APELLIDO` varchar(20) NOT NULL, `SEGUNDO_APELLIDO` varchar(20) NOT NULL, `EMAIL` varchar(20) NOT NULL
)
ALTER TABLE `ALUMNO` ADD PRIMARY KEY (`ALUMNO_ID`);
ALTER TABLE `ALUMNO` MODIFY `ALUMNO_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `USUARIO_ROLE` (`ROLE_ID` int NOT NULL, `ROLE_NAME` varchar(10) NOT NULL
) 
ALTER TABLE `USUARIO_ROLE` ADD PRIMARY KEY (`ROLE_ID`);
ALTER TABLE `USUARIO_ROLE` MODIFY `ROLE_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `ES_PROV` (`ES_PROV_ID` int NOT NULL, `ES_PROV_CD` varchar(2) NOT NULL, `ES_PROV_NM` varchar(30) NOT NULL
) 
ALTER TABLE `ES_PROV` ADD PRIMARY KEY (`ES_PROV_ID`);
ALTER TABLE `ES_PROV` MODIFY `ES_PROV_ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;


CREATE TABLE `DIRECCION_TYPE` (`DIRECCION_TYPE_ID` int NOT NULL, `DIRECCION_TYPE_CODE` varchar(1) NOT NULL, `DIRECCION_TYPE_TEXT` varchar(20) NOT NULL
) 
ALTER TABLE `DIRECCION_TYPE` ADD PRIMARY KEY (`DIRECCION_TYPE_ID`);
ALTER TABLE `DIRECCION_TYPE` MODIFY `DIRECCION_TYPE_ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;


CREATE TABLE `DIRECCION` (`DIRECCION_ID` int NOT NULL, `DIRECCION_TYPE_ID` int NOT NULL, `ALUMNO_ID` int NOT NULL, `DIREC_LINEA1` varchar(100) NOT NULL, `DIREC_LINEA2` varchar(100) NOT NULL, `CIUDAD` varchar(100) NOT NULL, `ES_PROV_ID` int NOT NULL
) 
ALTER TABLE `DIRECCION` ADD PRIMARY KEY (`DIRECCION_ID`);
ALTER TABLE `DIRECCION` MODIFY `DIRECCION_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `ES_CIUDAD` (`ES_CIUDAD_ID` int NOT NULL, `ES_CIUDAD_NM` varchar(30) NOT NULL, `CP` varchar(5) NOT NULL, `ES_PROV_ID` int NOT NULL
)
ALTER TABLE `ES_CIUDAD` ADD PRIMARY KEY (`ES_CIUDAD_ID`);
ALTER TABLE `ES_CIUDAD` MODIFY `ES_CIUDAD_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `TELEFONO_TYPE` (`TELEFONO_TYPE_ID` int NOT NULL, `TELEFONO_TYPE_CD` varchar(1) NOT NULL,
`TELEFONO_TYPE_TEXT` varchar(20) NOT NULL
) 
ALTER TABLE `TELEFONO_TYPE` ADD PRIMARY KEY (`TELEFONO_TYPE_ID`);
ALTER TABLE `TELEFONO_TYPE` MODIFY `TELEFONO_TYPE_ID` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;


CREATE TABLE `TELEFONO` (`TELEFONO_ID` int NOT NULL, `TELEFONO_TYPE_ID` int NOT NULL, `ALUMNO_ID` int NOT NULL
) 
ALTER TABLE `TELEFONO` ADD PRIMARY KEY (`TELEFONO_ID`);
ALTER TABLE `TELEFONO` MODIFY `TELEFONO_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `APP_USUARIO` (`APP_USUARIO_ID` int NOT NULL, `USUARIO_NAME` varchar(15) NOT NULL,
`PASSWORD` varchar(15) NOT NULL
)
ALTER TABLE `APP_USUARIO` ADD PRIMARY KEY (`APP_USUARIO_ID`);
ALTER TABLE `APP_USUARIO` MODIFY `APP_USUARIO_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `ITEM` (`ITEM_ID` int NOT NULL, `ITEM_NUMERO` varchar(10) NOT NULL,
`ITEM_SHORT_DESC` varchar(100) NOT NULL, `ITEM_LONG_DESC` varchar(100) NOT NULL
) 
ALTER TABLE `ITEM` ADD PRIMARY KEY (`ITEM_ID`);
ALTER TABLE `ITEM` MODIFY `ITEM_ID` int NOT NULL AUTO_INCREMENT;



CREATE TABLE `ALUMNO_ORDER` (`ALUMNO_ORDER_ID` int NOT NULL, `ALUMNO_ID` int NOT NULL,
`ORDER_NUMERO` varchar(30) NOT NULL, `ORDER_DESCRIPTION` varchar(100) NOT NULL
)
ALTER TABLE `ALUMNO_ORDER` ADD PRIMARY KEY (`ALUMNO_ORDER_ID`);
ALTER TABLE `ALUMNO_ORDER` MODIFY `ALUMNO_ORDER_ID` int NOT NULL AUTO_INCREMENT;


CREATE TABLE `ORDER_ITEM` (
  `ALUMNO_ORDER_ID` int NOT NULL,
  `ALUMNO_ORDER` int NOT NULL,
  `ITEM_ID` int(11) NOT NULL
) 

CREATE TABLE `APP_USUARIO_ROLE` (
  `APP_USUARIO_ID` int NOT NULL,
  `USUARIO_ROLE_ID` int NOT NULL
)


INSERT INTO `DIRECCION_TYPE` (`DIRECCION_TYPE_ID`, `DIRECCION_TYPE_CODE`, `DIRECCION_TYPE_TEXT`) VALUES
(1, 'C', 'Casa'),
(2, 'T', 'Trabajo'),
(3, 'M', 'Movil');


INSERT INTO `ES_PROV` (`ES_PROV_ID`, `ES_PROV_CD`, `ES_PROV_NM`) VALUES
(1, 'MA', 'Madrid'),
(2, 'BA', 'Barcelona'),
(3, 'SE', 'Sevilla'),
(4, 'VA', 'Valencia'),
(5, 'ML', 'Malaga'),
(6, 'CA', 'Cadiz'),
(7, 'ZA', 'Zaragoza'),
(8, 'AL', 'Alicante'),
(9, 'VZ', 'Vizcaya'),
(10, 'GU', 'Guipuzcoa'),
(11, 'GR', 'Granada'),
(12, 'GI', 'Girona'),
(13, 'JA', 'Jaen'),
(14, 'AM', 'Almeria'),
(15, 'AB', 'Alaba'),
(16, 'TA', 'Tarragona'),
(17, 'TO', 'Toledo'),
(18, 'CO', 'La Coruña'),
(19, 'HU', 'Huelva'),
(20, 'BA', 'Badajoz');


INSERT INTO `TELEFONO_TYPE` (`TELEFONO_TYPE_ID`, `TELEFONO_TYPE_CD`, `TELEFONO_TYPE_TEXT`) VALUES
(1, 'C', 'Casa'),
(2, 'T', 'Trabajo'),
(3, 'M', 'Movil');


COMMIT;
*/

CREATE TABLE SEQUENCE (
    SEQ_NAME varchar(50) NOT NULL,
    SEQ_COUNT decimal(15,0) NOT NULL
);

CREATE TABLE ALUMNO (
    ALUMNO_ID int NOT NULL,
    NOMBRE varchar(255),
    PRIMER_APELLIDO varchar(255),
    SEGUNDO_APELLIDO varchar(255),
    EMAIL varchar(255),
    PRIMARY KEY (ALUMNO_ID)
);

CREATE TABLE USUARIO_ROLE (
    ROLE_ID int NOT NULL,
    ROLE_NAME varchar(10) NOT NULL,
    PRIMARY KEY (ROLE_ID)
   
);

CREATE TABLE ES_PROV (
    ES_PROV_ID int NOT NULL,
    ES_PROV_CD varchar(2) NOT NULL,
    ES_PROV_NM varchar(30) NOT NULL,
    PRIMARY KEY (ES_PROV_ID)
);

CREATE TABLE DIRECCION_TYPE (
    DIRECCION_TYPE_ID int NOT NULL,
    DIRECCION_TYPE_CODE varchar(1) NOT NULL,
    DIRECCION_TYPE_TEXT varchar(20) NOT NULL,
    PRIMARY KEY (DIRECCION_TYPE_ID),
    
);

CREATE TABLE DIRECCION (
    DIRECCION_ID int NOT NULL,
    DIRECCION_TYPE_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    PRIMARY KEY (DIRECCION_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID),
FOREIGN KEY (DIRECCION_TYPE_ID) REFERENCES DIRECCION_TYPE(DIRECCION_TYPE_ID)
);

CREATE TABLE ES_CIUDAD (
    ES_CIUDAD_ID int NOT NULL,
    ES_CIUDAD_NM varchar(30) NOT NULL,
    CP varchar(5) NOT NULL,
    ES_PROV_ID int NOT NULL
    PRIMARY KEY (ES_CIUDAD_ID),
    FOREIGN KEY (ES_PROV_ID) REFERENCES ES_PROV(ES_PROV_ID)
);

CREATE TABLE TELEFONO_TYPE (
    TELEFONO_TYPE_ID int NOT NULL,
    TELEFONO_TYPE_CD varchar(1) NOT NULL,
    TELEFONO_TYPE_TEXT varchar(20) NOT NULL,
    PRIMARY KEY (TELEFONO_TYPE_ID)
);

CREATE TABLE TELEFONO (
    TELEFONO_ID int NOT NULL,
    TELEFONO_TYPE_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    PRIMARY KEY (TELEFONO_ID),
    FOREIGN KEY (TELEFONO_TYPE_ID) REFERENCES TELEFONO_TYPE(TELEFONO_TYPE_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID)
);

CREATE TABLE APP_USUARIO (
    APP_USUARIO_ID int NOT NULL,
    USUARIO_NAME varchar(15),
    PASSWORD varchar(15),
    PRIMARY KEY (APP_USUARIO_ID)
);

CREATE TABLE ITEM (
    ITEM_ID int NOT NULL,
    ITEM_NUMERO varchar(10) NOT NULL,
    ITEM_SHORT_DESC varchar(100) NOT NULL,
    ITEM_LONG_DESC varchar(100) NOT NULL,
    PRIMARY KEY (ITEM_ID)
);

CREATE TABLE ALUMNO_ORDER (
    ALUMNO_ORDER_ID int NOT NULL,
    ALUMNO_ID int NOT NULL,
    ORDER_NUMERO varchar(255),
    ORDER_DESCRIPTION varchar(255),
    PRIMARY KEY (ALUMNO_ORDER_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID)
);

CREATE TABLE ORDER_ITEM (
    ALUMNO_ORDER_ID int NOT NULL,
    ALUMNO_ORDER int NOT NULL,
    ITEM_ID int NOT NULL,
    PRIMARY KEY (ALUMNO_ORDER),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (ALUMNO_ORDER_ID) REFERENCES ALUMNO_ORDER(ALUMNO_ORDER_ID)
);

CREATE TABLE APP_USUARIO_ROLE (
    APP_USUARIO_ID int NOT NULL,
    ROLE_ID int NOT NULL,
    PRIMARY KEY (APP_USUARIO_ID, ROLE_ID),
    FOREIGN KEY (APP_USUARIO_ID) REFERENCES APP_USUARIO(APP_USUARIO_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES USUARIO_ROLE(ROLE_ID)
);







